import wolframResponse from '../wolfram-response'

export default {
  actors: wolframResponse,
  albums: wolframResponse,
  architecture: wolframResponse,
  artists: wolframResponse,
  astronomy: wolframResponse,
  biology: wolframResponse,
  books: wolframResponse,
  characters: wolframResponse,
  companies: wolframResponse,
  comparatives: wolframResponse,
  composers: wolframResponse,
  date: wolframResponse,
  directors: wolframResponse,
  distance: wolframResponse,
  food: wolframResponse,
  games: wolframResponse,
  genres: wolframResponse,
  geography: wolframResponse,
  geometry: wolframResponse,
  history: wolframResponse,
  holidays: wolframResponse,
  institutions: wolframResponse,
  languages: wolframResponse,
  math: wolframResponse,
  movies: wolframResponse,
  namemeaning: wolframResponse,
  object: wolframResponse,
  painters: wolframResponse,
  paintings: wolframResponse,
  person: wolframResponse,
  physics: wolframResponse,
  physiography: wolframResponse,
  politicians: wolframResponse,
  songs: wolframResponse,
  sportsevent: wolframResponse,
  sportsmen: wolframResponse,
  sportsteam: wolframResponse,
  superlative: wolframResponse,
  unknown: wolframResponse,
  words: wolframResponse,
  writers: wolframResponse
}
