version: '2'
services:
  jasper-api-test:
    build: .
    command: npm run test:watch
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - cache-test
      - db-test
      - statsd-test
    links:
      - cache-test
      - db-test
      - statsd-test
    env_file: .env
    environment:
      - DATABASE_NAME=test
      - DATABASE_HOST=db-test
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_ACCESS_KEY=test
      - NODE_ENV=test
      - REDIS_HOST=cache-test
      - REDIS_PARTITION=test
      - REDIS_PORT=6379
      - SECRET=secret
      - STATSD_HOST=statsd-test

  cache-test:
    expose:
      - 6379
    image: redis:latest

  db-test:
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
    expose:
      - 5432
    image: postgres:latest

  statsd-test:
    expose:
      - 80
      - 8125/udp
      - 8126
    image: hopsoft/graphite-statsd:latest
    restart: always
